Repository nirmata/reports-server, pull requests merged in 2025-04, with the labels that each got.

#82 [NDEV-22428][NDEV-22388]: Tolerations and NodeSelector support for the etcd
  charts/reports-server/README.md
  charts/reports-server/templates/etcd.yaml
  charts/reports-server/values.yaml
  config/install-etcd.yaml
  config/install.yaml
  go.mod
  pkg/storage/db/new.go
Labels: release-0.1, cherry-pick-required

#89 add quota limit and secret configuration for custom ssl
  charts/reports-server/Chart.yaml
  charts/reports-server/README.md
  charts/reports-server/templates/deployment.yaml
  charts/reports-server/templates/etcd.yaml
  charts/reports-server/values.yaml
  config/install-etcd.yaml
  config/install.yaml
Labels: cherry-pick-required

#88 [NDEV-22437]: replica DB support in the reports server
  .gitignore
  charts/reports-server/Chart.yaml
  charts/reports-server/README.md
  charts/reports-server/templates/_helpers.tpl
  charts/reports-server/templates/deployment.yaml
  charts/reports-server/values.yaml
  config/install-etcd.yaml
  config/install.yaml
  go.mod
  go.sum
  pkg/app/opts/options.go
  pkg/storage/db/cephr.go
  pkg/storage/db/cpolr.go
  pkg/storage/db/ephr.go
  pkg/storage/db/multiDB.go
  pkg/storage/db/new.go
  pkg/storage/db/polr.go
Labels: cherry-pick-required

#91 Cherry pick 89
  charts/reports-server/Chart.yaml
  charts/reports-server/README.md
  charts/reports-server/templates/deployment.yaml
  charts/reports-server/templates/etcd.yaml
  charts/reports-server/values.yaml
  config/install-etcd.yaml
  config/install.yaml
Labels: cherry-pick-complete

#92 Cherry-pick #90
  go.mod
  go.sum
  pkg/storage/db/new.go
  pkg/storage/db/new_test.go
Labels: cherry-pick-complete

#94 Ndev 22499: removing the default value of Port
  charts/reports-server/Chart.yaml
  charts/reports-server/README.md
  charts/reports-server/values.yaml
  config/install-etcd.yaml
  config/install.yaml
  pkg/storage/db/new_test.go
Labels: cherry-pick-required
